export const ICON_NAMES = {
  home: 'House',
  work: 'Briefcase',
  knowledge: 'BookOpen',
  documents: 'FileText',
  admin: 'Gear',
  notifications: 'Bell',
  user: 'User',
  search: 'MagnifyingGlass',
  filter: 'Funnel',
  upload: 'Upload',
  download: 'Download',
  check: 'Check',
  warning: 'Warning',
  error: 'XCircle',
  info: 'Info',
  expand: 'CaretDown',
  collapse: 'CaretUp',
  forward: 'ArrowRight',
  back: 'ArrowLeft',
  star: 'Star',
  starFilled: 'StarFill',
  clock: 'Clock',
  calendar: 'Calendar',
  more: 'DotsThree',
  external: 'ArrowSquareOut',
  copy: 'Copy',
  refresh: 'ArrowClockwise',
  trash: 'Trash',
  edit: 'Pencil',
  plus: 'Plus',
  lock: 'Lock',
  eye: 'Eye',
  eyeOff: 'EyeSlash',
  folder: 'Folder',
  close: 'X',
  menu: 'List',
} as const;

export const ICON_SIZE = {
  sm: 16,
  md: 20,
  lg: 24,
} as const;
