export const ROUTES = {
  login: "/login",
  loginForgot: "/login/forgot",
  loginReset: "/login/reset",
  home: "/home",
  work: "/work",
  workInbox: "/work/inbox",
  workActive: "/work/active",
  workWaiting: "/work/waiting",
  workApprovals: "/work/approvals",
  workArchive: "/work/archive",
  workNew: "/work/new",
  caseOverview: "/work/:caseId",
  caseChecklist: "/work/:caseId/checklist",
  caseDocuments: "/work/:caseId/documents",
  caseNotes: "/work/:caseId/notes",
  caseActivity: "/work/:caseId/activity",
  caseDecisionSupport: "/work/:caseId/decision-support",
  caseDraft: "/work/:caseId/draft",
  caseSend: "/work/:caseId/send",
  caseApproval: "/work/:caseId/approval",
  knowledge: "/knowledge",
  knowledgeRegulations: "/knowledge/regulations",
  knowledgeProcedures: "/knowledge/procedures",
  knowledgeTemplates: "/knowledge/templates",
  knowledgeFAQs: "/knowledge/faqs",
  documents: "/documents",
  documentsUpload: "/documents/upload",
  documentsIndexStatus: "/documents/index-status",
  documentDetail: "/documents/:id",
  admin: "/admin",
  adminCorpusHealth: "/admin/corpus-health",
  adminCorpusInventory: "/admin/corpus-inventory",
  adminAudit: "/admin/audit",
  adminJobs: "/admin/jobs",
  adminBenchmarks: "/admin/benchmarks",
  adminDev: "/admin/dev",
  adminUsers: "/admin/users",
  adminUserDetail: "/admin/users/:id",
} as const;

export const MODULE_LABELS: Record<string, string> = {
  "/home": "Startseite",
  "/work": "Meine Arbeit",
  "/knowledge": "Wissen",
  "/documents": "Dokumentenverwaltung",
  "/admin": "Verwaltung",
};
